게시글, 유저, 댓글 api에서 수정과 삭제 권한 설정 추가
f-lab-edu/fastapi-server pull request #33
Opened 2024-03-06 17:25 UTC by 8bitHermitcrab

2024-03-07 08:12 UTC, heumsi requested changes
코멘트 확인해보시고, 전체적으로 지금 코드 동작이 잘 되는지 한번 확인해주세요.
제 생각에는 댓글 내용 수정 API는 아예 동작 안하고 오류가 날거 같은데.. 확인 한번 해주세요~

2024-03-07 08:12 UTC, heumsi commented on api/api_schema.py
> +    access_token_expire_days: int
얘는 API Schema가 아닌데, 이 파일에 있는게 좋아보이진 않습니다.
별도의 `config.py` 에 두는건 어떨까요?

2024-03-09 05:54 UTC, heumsi commented
제 로컬에 클론 받아서 하나씩 실행해보겠습니다.

일단 앱 기동하면 다음과 같은 에러가 뜹니다.

```
uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [23029] using StatReload
2024-03-09 14:45:24,192 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-09 14:45:24,193 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("post")
2024-03-09 14:45:24,193 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-03-09 14:45:24,193 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("user")
2024-03-09 14:45:24,193 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-03-09 14:45:24,193 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("comment")
2024-03-09 14:45:24,193 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-03-09 14:45:24,193 INFO sqlalchemy.engine.Engine COMMIT
INFO:     Started server process [23031]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:53775 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:53775 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:53775 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:53829 - "POST /api/users/ HTTP/1.1" 422 Unprocessable Entity
2024-03-09 14:48:40,312 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-09 14:48:40,314 INFO sqlalchemy.engine.Engine INSERT INTO user (user_id, password, nickname, role, created_at) VALUES (?, ?, ?, ?, ?)
2024-03-09 14:48:40,314 INFO sqlalchemy.engine.Engine [generated in 0.00014s] ('ydrah', '$2b$12$eBkOVgnoaecS6245WwWSCOwT.0gWekkE6kvmBZWBgJ08k759osEum', 'yd', 'member', '2024-03-09 05:48:40.312300')
2024-03-09 14:48:40,314 INFO sqlalchemy.engine.Engine COMMIT
INFO:     127.0.0.1:53832 - "POST /api/users/ HTTP/1.1" 201 Created
INFO:     127.0.0.1:53854 - "GET /api/users/ydrah/posts/?page=1 HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:53858 - "GET /api/users/ydrah/posts/?page=1 HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:53858 - "GET /api/users/ydrah/posts/?page=1 HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:53860 - "GET /api/users/ydrah/posts/?page=1 HTTP/1.1" 422 Unprocessable Entity
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [23031]
INFO:     Stopping reloader process [23029]
(.venv) ~/Desktop/heumsi/projects/f-lab/fastapi-server (main ✔)
(.venv) ~/Desktop/heumsi/projects/f-lab/fastapi-server (main ✔)
(.venv) ~/Desktop/heumsi/projects/f-lab/fastapi-server (main ✔) git switch feature/auth
branch 'feature/auth' set up to track 'origin/feature/auth'.
새로 만든 'feature/auth' 브랜치로 전환합니다
(.venv) ~/Desktop/heumsi/projects/f-lab/fastapi-server (feature/auth ✔)
(.venv) ~/Desktop/heumsi/projects/f-lab/fastapi-server (feature/auth ✔)
(.venv) ~/Desktop/heumsi/projects/f-lab/fastapi-server (feature/auth ✔)
(.venv) ~/Desktop/heumsi/projects/f-lab/fastapi-server (feature/auth ✔) uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [24880] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/main.py", line 4, in <module>
    from api import comment, post, user
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/api/comment.py", line 10, in <module>
    from common import api_key_header, check_access_token
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/common.py", line 8, in <module>
    from config import Settings
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/config.py", line 1, in <module>
    from pydantic_settings import BaseSettings
ModuleNotFoundError: No module named 'pydantic_settings'
```

`pydantic_settings` 모듈을 `pyproject.toml` 에 추가를 안하신거 같군요. 추가해주세요.

2024-03-09 05:56 UTC, heumsi commented
위 모듈 제가 수동으로 설치 후 다시 실행하면 다음과 같은 에러가 납니다.

```
uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [25712] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/.venv/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.0/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/main.py", line 4, in <module>
    from api import comment, post, user
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/api/comment.py", line 10, in <module>
    from common import api_key_header, check_access_token
  File "/Users/user/Desktop/heumsi/projects/f-lab/fastapi-server/common.py", line 14, in <module>
    with open("config.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
```

`config.yaml` 는 `.gitignore` 에 추가하셔서, git에 안올라온거 같은데, 제가 이 앱을 기동하려면 어떻게 해야 하나요?

2024-03-11 02:49 UTC, f-lab-ydrah commented
피드백 드립니다.

1. 유저 생성할 때 Role을 클라이언트 쪽이 지정할 수 있게 되어있네요. 기본적으로 유저는 모두 유저 Role로 만들어져야 합니다. 유저가 직접 어드민 Role로 생성하면 이상하잖아요~? ㅎㅎ

<img width="1438" alt="image" src="https://github.com/f-lab-edu/fastapi-server/assets/110903858/274edb97-46e7-40d0-9abd-1567a8360959">

2. 아래처럼 유저를 생성했더니 500 에러가 납니다.

<img width="1154" alt="image" src="https://github.com/f-lab-edu/fastapi-server/assets/110903858/405d79d0-5800-4d1c-91eb-d62ed17d9708">

로그를 보니 다음처럼 되어 있더군요.

```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.user_id
[SQL: INSERT INTO user (user_id, password, nickname, role, created_at) VALUES (?, ?, ?, ?, ?)]
[parameters: ('ydrah', '$2b$12$jb/EE4r19G.mFMQpgAevzOXGn3Iyi0yTKa6UxH5l0teh1LJdiB646', 'ydrah', 'member', '2024-03-11 02:46:26.817665')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

id가 같으면 409 에러를 내야 하는데, 이 부분이 누락되어 있는거 같아요.

3. 다른 아이디로 생성 시도했으나, 이번엔 422 에러가 납니다. 응답 메시지를 봐도 어떤게 문제인지 모르겠습니다.

<img width="1170" alt="image" src="https://github.com/f-lab-edu/fastapi-server/assets/110903858/7931efc6-a6a8-4afe-ac43-33193834479b">

2024-03-11 02:50 UTC, f-lab-ydrah commented
전체적으로 실행해보시고, 유저 생성부터 코멘트까지, 전체적으로 모든 API를 한번 실행하고 잘 동작하는지 테스트 하신 뒤 리뷰 요청 부탁드립니다.

2024-03-11 02:50 UTC, f-lab-ydrah commented
API 테스트로는 Postman을 사용해보셔요~ ㅎㅎ

https://www.postman.com/

2024-03-12 09:13 UTC, merged