유저 로그인 테스트 코드 추가
f-lab-edu/fastapi-server pull request #37
Opened 2024-03-23 14:07 UTC by 8bitHermitcrab

2024-03-26 02:18 UTC, f-lab-ydrah requested changes
코멘트 한번 봐 주시고... 지금 테스트 다 통과하는지도 한번 봐주세요.

2024-03-26 02:18 UTC, f-lab-ydrah commented on test/user/test_crud.py
> +    assert response.json().get("detail") == "유저 생성 성공"
database에 실제로 user가 추가되었는지 검증이 추가로 있어야 겠네요.

2024-03-27 11:20 UTC, f-lab-ydrah commented on test/user/test_login.py
> +    assert response.json().get("detail") == "아이디 혹은 비밀번호가 맞지 않습니다."
```suggestion
    res_data = response.json()
    assert res_data["detail"] == "아이디 혹은 비밀번호가 맞지 않습니다."
```

2024-03-27 11:21 UTC, f-lab-ydrah commented on test/user/test_login.py
> +    response = client.post("/api/users/login", json=login_data)
```suggestion
    response = client.post("/api/users/login", json=login.dict())
```

2024-03-27 11:39 UTC, f-lab-ydrah approved these changes

2024-04-01 00:37 UTC, heumsi approved these changes
리뷰할 코드 양이 너무 많아, 제가 일일이 보지는 못했습니다.

다음부터는 더 작게, 더 자주 PR 만드시고 리뷰 요청 해주세요. (현업에서 이렇게 크게 변경 사항을 만들
어서 리뷰 요청 하시면, 팀원에게 눈총 받을 수 있습니다 ㅋㅋ)

일단 테스트는 성공해서 Approve 드리고, 코멘트만 확인하시고 이 부분 반영해서 머지해주세요~
PR 제목도 적절히 수정해주시구요~

2024-04-01 00:37 UTC, heumsi commented on tests/api/test_comment.py
> +    assert response.status_code == 201
실제 DB에 생성되었는지도 검증해야겠죠?

2024-04-01 00:37 UTC, heumsi commented on tests/api/test_comment.py
> +    assert response.status_code == 201
다른 곳도 마찬가지 입니다 ㅎㅎ

2024-04-01 00:37 UTC, heumsi commented on tests/api/test_comment.py
> +def test_success_edit_comment(setup_test_environment):
```suggestion
def test_success_edit_comment():
```

`autouse=True` 인 fixture를 쓰면, 일일이 파라미터로 안받아도 됩니다.

2024-04-01 00:37 UTC, heumsi commented on tests/conftest.py
> +    os.environ["DATABASE_URL"] = "sqlite:///tests.db"
인메모리를 쓰는건 어떨까요?

2024-04-01 05:48 UTC, merged